CREATE SEQUENCE msgID_seq START WITH 0; /* TODO: CHANGE TO BE CORRECT*/
CREATE SEQUENCE dept_seq START WITH 0;

CREATE LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION newMsg()
RETURNS "trigger" AS
$BODY$
BEGIN
NEW.msg_ID = nextval('msgID_seq');

RETURN NEW;

END;
$BODY$
LANGUAGE plpgsql VOLATILE;

CREATE TRIGGER newMessage BEFORE INSERT
ON MSG FOR EACH ROW
EXECUTE PROCEDURE newMsg();


CREATE LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION newDept()
RETURNS "trigger" AS
$BODY$
BEGIN
NEW.dept_ID = nextval('dept_seq');

RETURN NEW;

END;
$BODY$
LANGUAGE plpgsql VOLATILE;

CREATE TRIGGER newDepartment BEFORE INSERT
ON DEPARTMENTS FOR EACH ROW
EXECUTE PROCEDURE newDept();